from .analyzer import OllamaVideoAnalyzer
from .diagnostics import check_environment, check_ffmpeg
from .exceptions import (
    AudioExtractionError,
    ConfigurationError,
    MissingDependencyError,
    ModelCapabilityError,
    ModelNotFoundError,
    OpenSceneSenseError,
    ProviderConnectionError,
    ResponseValidationError,
    TranscriptionError,
    VideoLoadError,
    VideoMetadataError,
)
from .frame_selectors import AllFrameSelector, DynamicFrameSelector, UniformFrameSelector
from .models import (
    ANALYSIS_RESULT_SCHEMA,
    AnalysisMetadata,
    AnalysisPrompts,
    AnalysisResult,
    AudioSegment,
    Frame,
    FrameAnalysis,
    ModelsUsed,
    PerformanceMetadata,
    SceneType,
    SelectionMetadata,
    SelectionReason,
    SummaryResult,
    TimelineEvent,
    UsageMetadata,
    VideoMetadata,
    analysis_result_schema,
)
from .progress import ProgressEvent
from .transcriber import AudioTranscriber, WhisperTranscriber

__version__ = "1.2.0"

__all__ = [
    "ANALYSIS_RESULT_SCHEMA",
    "AllFrameSelector",
    "AnalysisMetadata",
    "AnalysisPrompts",
    "AnalysisResult",
    "AudioExtractionError",
    "AudioSegment",
    "AudioTranscriber",
    "ConfigurationError",
    "DynamicFrameSelector",
    "Frame",
    "FrameAnalysis",
    "MissingDependencyError",
    "ModelCapabilityError",
    "ModelNotFoundError",
    "ModelsUsed",
    "OllamaVideoAnalyzer",
    "OpenSceneSenseError",
    "PerformanceMetadata",
    "ProgressEvent",
    "ProviderConnectionError",
    "ResponseValidationError",
    "SceneType",
    "SelectionMetadata",
    "SelectionReason",
    "SummaryResult",
    "TimelineEvent",
    "TranscriptionError",
    "UniformFrameSelector",
    "UsageMetadata",
    "VideoLoadError",
    "VideoMetadata",
    "VideoMetadataError",
    "WhisperTranscriber",
    "analysis_result_schema",
    "check_environment",
    "check_ffmpeg",
]
